# checks and formatting for rust code
repos:
- repo: local
  hooks:
    - id: cargo-fmt
      name: cargo fmt
      entry: cargo fmt --
      language: system
      types: [rust]
      pass_filenames: false
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: clippy

# checks and formatting for python code
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.4
  hooks:
    - id: ruff-format  # Formatter
    - id: ruff  # Linter
      args: [--fix, --exit-non-zero-on-fix]
